### ISSUE TITLE
documentation of VPrimer

### ISSUE THREAD

**Issue by aiqubo** [qhtjrmin/VPrimer#1]
Hi, I am interested in using this tool and am looking for documentation to use the VPrimer, Can you please post a readme on how to run? 

"~/VPrimer/src/virus_primer/vprimer -i ~/VPrimer/input_test/test_virus.txt -o ~/VPrimer/output/virus_primer_output.txt -d ~/VPrimer/output -s 7
<Files>
....
....
## Stage 4_1 (k = 1) : general cross hybridization building
0 / 350250 : *TGGCAATGCTGTACTTGAAC TGGCAATGC+0+20
100000 / 350250 : TGGAGAGACAAAGCCAGTGT TGGAGAGAC+0+20
200000 / 350250 : *CCAGGCCCGAACGAGAGAAA CCAGGCCCG+0+20
300000 / 350250 : *GTCAGCCCAAAGAGTGTGAT GTCAGCCCA+0+20
Elapsed time (Stage 4_1, k = 1) : 22.7992 sec

## Stage 4_2 (k = 1) : general cross hybridization preparing
minimum_seedHr: 1 maximum_seedHr: 66
minimum_seedHf: 1 maximum_seedHf: 65
878 MB is utilized. 7900000 workload
Elapsed time (Stage 4_2, k = 1) : 33.3188 sec

## Stage 4_3 (k = 1) : general cross hybridization probing

Segmentation fault (core dumped)"

How to fix it ? thanks

qubo

**Comment by Hajin-Jeon** [comment]
Hello, Qubo. I'm sorry for late response. I wrote documentation at here, and fixed some bugs including segmentation fault you mentioned: https://github.com/Hajin-Jeon/VPrimer

Furthermore, I'm sorry for the codes of "find primer pair having at least one proper probe" and "find final primer-probe sets" are not provided in GitHub. It might be more helpful to refer to the GPrimer paper regarding this aspect: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04133-4

**Comment by aiqubo** [comment]
> Hello, Qubo. I'm sorry for late response. I wrote documentation at here, and fixed some bugs including segmentation fault you mentioned: https://github.com/Hajin-Jeon/VPrimer
> 
> Furthermore, I'm sorry for the codes of "find primer pair having at least one proper probe" and "find final primer-probe sets" are not provided in GitHub. It might be more helpful to refer to the GPrimer paper regarding this aspect: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04133-4

OK, Thanks, work now
